### ISSUE TITLE
Battle feedback

### ISSUE THREAD

**Issue by martinacantaro** [lambdaclass/champions_of_mirra#256]
Add VFX for the skills
Work with Salva to add sounds
Add something when the champion is hit
Add healthbars
Add energy bars
Add something to know when the character is dealing its ulti

**Comment by tkz00** [comment]
We divided this issue in smaller ones:

- [ ] [Read and Display Battle steps](https://github.com/lambdaclass/champions_of_mirra/issues/279)
- [ ] [Unit UI in Battle](https://github.com/lambdaclass/champions_of_mirra/issues/280)
- [ ] [Audio feedback to actions in the battle](https://github.com/lambdaclass/champions_of_mirra/issues/281)
- [ ] [Visual effects for battle](https://github.com/lambdaclass/champions_of_mirra/issues/282)
- [ ] [Movement feedback in battle](https://github.com/lambdaclass/champions_of_mirra/issues/283)
